# Generated by Django 3.2 on 2022-09-17 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_jobs', '0004_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'vacancies'},
        ),
    ]
